REPORT = 2
using Weave, Dates, CSV, DataFrames



PARAM_FILE = "data/params.csv"

df = CSV.read(PARAM_FILE,DataFrame)
df = filter(row->row.cell==REPORT,df)
sort!(df,"cycle")


dt = Dates.now()
mydt = Dates.format(dt, "yyyy-mm-dd HH:MM:SS")

report_name = "reports/detailedreportVAH$REPORT.jl"
io = open(report_name,"w")

println(io,"#' # Detailed Report for VAH $REPORT")
println(io,"#' #### Generated by Alec Bills at $mydt")
println(io,"#+ echo=false")
println(io,"using Plots,DataFrames,CSV")
println(io,"pdf = CSV.read(\"../data/params.csv\",DataFrame)")
println(io,"pdf=filter(row->row.cell==$REPORT,pdf)")
println(io,"sort!(pdf,:cycle)")
println(io,"nothing")

for r in 1:nrow(df)
    println(io,"#' #### VAH: $REPORT; CYCLE: $(df.cycle[r])")
    println(io,"#+ echo=false")
    println(io,"cell=$(REPORT)")
    println(io,"cycle=$(df.cycle[r])")
    println(io,"params = pdf[$r,:]")
    println(io,"include(\"evaluatorsetup.jl\")")
    println(io,"p1 = plot(df.times,df.EcellV,label=\"Experiment\",xlabel=\"Time[s]\",ylabel=\"Voltage[V]\")")
    println(io,"plot!(p1,df.times[1:end-1],V,label=\"Simulation\")")
    println(io,"p1")
end

close(io)

mkdir("reports/figs")

weave("/Users/alecbills/ResearchProjects/CellFitElectrolyte/reports/detailedreportVAH$REPORT.jl"; doctype = "md2html",fig_path="figs")

rm("reports/figs",recursive=true)
