#' # CellFit Summary Report
#' #### Generated by Alec Bills at 2022-07-21 20:01:23
#+ echo=false
using Plots,DataFrames,CSV
df = CSV.read("../data/params.csv",DataFrame)
nothing
#' #### VAH: 2.0
#+ echo=false
ndf = filter(row->row.cell==2.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 2.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 2.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 2.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 2.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 2.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 2.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 2.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 2.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 2.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 2.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 2.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 2.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 2.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 2.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 2.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 2.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 2.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 2.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 2.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 2.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 2.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 2.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 2.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 1.0
#+ echo=false
ndf = filter(row->row.cell==1.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 1.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 1.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 1.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 1.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 1.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 1.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 1.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 1.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 1.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 1.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 1.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 1.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 1.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 1.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 1.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 1.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 1.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 1.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 1.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 1.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 1.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 1.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 1.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 5.0
#+ echo=false
ndf = filter(row->row.cell==5.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 5.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 5.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 5.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 5.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 5.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 5.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 5.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 5.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 5.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 5.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 5.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 5.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 5.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 5.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 5.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 5.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 5.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 5.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 5.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 5.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 5.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 5.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 5.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 6.0
#+ echo=false
ndf = filter(row->row.cell==6.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 6.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 6.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 6.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 6.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 6.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 6.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 6.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 6.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 6.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 6.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 6.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 6.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 6.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 6.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 6.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 6.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 6.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 6.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 6.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 6.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 6.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 6.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 6.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 7.0
#+ echo=false
ndf = filter(row->row.cell==7.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 7.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 7.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 7.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 7.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 7.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 7.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 7.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 7.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 7.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 7.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 7.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 7.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 7.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 7.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 7.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 7.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 7.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 7.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 7.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 7.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 7.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 7.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 7.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 9.0
#+ echo=false
ndf = filter(row->row.cell==9.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 9.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 9.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 9.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 9.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 9.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 9.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 9.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 9.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 9.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 9.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 9.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 9.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 9.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 9.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 9.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 9.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 9.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 9.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 9.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 9.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 9.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 9.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 9.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 10.0
#+ echo=false
ndf = filter(row->row.cell==10.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 10.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 10.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 10.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 10.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 10.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 10.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 10.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 10.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 10.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 10.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 10.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 10.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 10.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 10.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 10.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 10.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 10.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 10.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 10.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 10.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 10.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 10.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 10.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 11.0
#+ echo=false
ndf = filter(row->row.cell==11.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 11.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 11.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 11.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 11.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 11.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 11.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 11.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 11.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 11.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 11.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 11.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 11.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 11.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 11.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 11.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 11.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 11.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 11.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 11.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 11.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 11.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 11.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 11.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 12.0
#+ echo=false
ndf = filter(row->row.cell==12.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 12.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 12.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 12.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 12.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 12.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 12.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 12.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 12.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 12.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 12.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 12.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 12.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 12.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 12.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 12.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 12.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 12.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 12.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 12.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 12.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 12.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 12.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 12.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 13.0
#+ echo=false
ndf = filter(row->row.cell==13.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 13.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 13.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 13.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 13.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 13.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 13.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 13.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 13.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 13.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 13.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 13.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 13.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 13.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 13.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 13.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 13.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 13.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 13.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 13.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 13.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 13.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 13.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 13.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 15.0
#+ echo=false
ndf = filter(row->row.cell==15.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 15.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 15.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 15.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 15.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 15.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 15.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 15.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 15.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 15.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 15.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 15.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 15.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 15.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 15.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 15.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 15.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 15.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 15.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 15.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 15.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 15.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 15.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 15.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 16.0
#+ echo=false
ndf = filter(row->row.cell==16.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 16.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 16.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 16.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 16.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 16.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 16.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 16.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 16.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 16.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 16.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 16.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 16.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 16.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 16.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 16.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 16.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 16.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 16.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 16.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 16.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 16.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 16.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 16.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 17.0
#+ echo=false
ndf = filter(row->row.cell==17.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 17.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 17.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 17.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 17.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 17.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 17.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 17.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 17.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 17.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 17.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 17.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 17.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 17.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 17.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 17.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 17.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 17.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 17.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 17.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 17.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 17.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 17.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 17.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 20.0
#+ echo=false
ndf = filter(row->row.cell==20.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 20.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 20.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 20.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 20.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 20.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 20.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 20.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 20.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 20.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 20.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 20.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 20.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 20.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 20.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 20.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 20.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 20.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 20.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 20.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 20.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 20.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 20.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 20.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 22.0
#+ echo=false
ndf = filter(row->row.cell==22.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 22.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 22.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 22.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 22.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 22.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 22.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 22.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 22.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 22.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 22.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 22.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 22.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 22.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 22.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 22.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 22.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 22.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 22.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 22.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 22.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 22.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 22.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 22.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 23.0
#+ echo=false
ndf = filter(row->row.cell==23.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 23.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 23.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 23.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 23.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 23.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 23.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 23.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 23.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 23.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 23.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 23.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 23.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 23.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 23.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 23.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 23.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 23.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 23.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 23.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 23.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 23.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 23.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 23.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 24.0
#+ echo=false
ndf = filter(row->row.cell==24.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 24.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 24.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 24.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 24.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 24.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 24.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 24.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 24.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 24.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 24.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 24.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 24.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 24.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 24.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 24.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 24.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 24.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 24.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 24.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 24.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 24.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 24.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 24.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 25.0
#+ echo=false
ndf = filter(row->row.cell==25.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 25.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 25.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 25.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 25.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 25.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 25.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 25.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 25.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 25.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 25.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 25.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 25.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 25.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 25.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 25.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 25.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 25.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 25.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 25.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 25.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 25.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 25.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 25.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
#' #### VAH: 26.0
#+ echo=false
ndf = filter(row->row.cell==26.0,df)
sort!(ndf,"cycle")
nothing
#' #### VAH: 26.0, PARAMETER: θₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁻,xlabel="cycle",ylabel="θₛ⁻",legend=false)
#' #### VAH: 26.0, PARAMETER: θₑ
#+ echo=false
plot(ndf.cycle,ndf.θₑ,xlabel="cycle",ylabel="θₑ",legend=false)
#' #### VAH: 26.0, PARAMETER: θₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.θₛ⁺,xlabel="cycle",ylabel="θₛ⁺",legend=false)
#' #### VAH: 26.0, PARAMETER: R⁺
#+ echo=false
plot(ndf.cycle,ndf.R⁺,xlabel="cycle",ylabel="R⁺",legend=false)
#' #### VAH: 26.0, PARAMETER: R⁻
#+ echo=false
plot(ndf.cycle,ndf.R⁻,xlabel="cycle",ylabel="R⁻",legend=false)
#' #### VAH: 26.0, PARAMETER: β⁻
#+ echo=false
plot(ndf.cycle,ndf.β⁻,xlabel="cycle",ylabel="β⁻",legend=false)
#' #### VAH: 26.0, PARAMETER: β⁺
#+ echo=false
plot(ndf.cycle,ndf.β⁺,xlabel="cycle",ylabel="β⁺",legend=false)
#' #### VAH: 26.0, PARAMETER: βˢ
#+ echo=false
plot(ndf.cycle,ndf.βˢ,xlabel="cycle",ylabel="βˢ",legend=false)
#' #### VAH: 26.0, PARAMETER: k₀⁺
#+ echo=false
plot(ndf.cycle,ndf.k₀⁺,xlabel="cycle",ylabel="k₀⁺",legend=false)
#' #### VAH: 26.0, PARAMETER: k₀⁻
#+ echo=false
plot(ndf.cycle,ndf.k₀⁻,xlabel="cycle",ylabel="k₀⁻",legend=false)
#' #### VAH: 26.0, PARAMETER: εₛ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁻,xlabel="cycle",ylabel="εₛ⁻",legend=false)
#' #### VAH: 26.0, PARAMETER: εₑ⁻
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁻,xlabel="cycle",ylabel="εₑ⁻",legend=false)
#' #### VAH: 26.0, PARAMETER: εₑˢ
#+ echo=false
plot(ndf.cycle,ndf.εₑˢ,xlabel="cycle",ylabel="εₑˢ",legend=false)
#' #### VAH: 26.0, PARAMETER: εₑ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₑ⁺,xlabel="cycle",ylabel="εₑ⁺",legend=false)
#' #### VAH: 26.0, PARAMETER: εₛ⁺
#+ echo=false
plot(ndf.cycle,ndf.εₛ⁺,xlabel="cycle",ylabel="εₛ⁺",legend=false)
#' #### VAH: 26.0, PARAMETER: cₑ₀
#+ echo=false
plot(ndf.cycle,ndf.cₑ₀,xlabel="cycle",ylabel="cₑ₀",legend=false)
#' #### VAH: 26.0, PARAMETER: κ
#+ echo=false
plot(ndf.cycle,ndf.κ,xlabel="cycle",ylabel="κ",legend=false)
#' #### VAH: 26.0, PARAMETER: t⁺
#+ echo=false
plot(ndf.cycle,ndf.t⁺,xlabel="cycle",ylabel="t⁺",legend=false)
#' #### VAH: 26.0, PARAMETER: input_type
#+ echo=false
plot(ndf.cycle,ndf.input_type,xlabel="cycle",ylabel="input_type",legend=false)
#' #### VAH: 26.0, PARAMETER: input_value
#+ echo=false
plot(ndf.cycle,ndf.input_value,xlabel="cycle",ylabel="input_value",legend=false)
#' #### VAH: 26.0, PARAMETER: fval
#+ echo=false
plot(ndf.cycle,ndf.fval,xlabel="cycle",ylabel="fval",legend=false)
#' #### VAH: 26.0, PARAMETER: cell
#+ echo=false
plot(ndf.cycle,ndf.cell,xlabel="cycle",ylabel="cell",legend=false)
#' #### VAH: 26.0, PARAMETER: cycle
#+ echo=false
plot(ndf.cycle,ndf.cycle,xlabel="cycle",ylabel="cycle",legend=false)
