
using Weave
using Dates
using CSV,DataFrames

PARAM_FILE = "data/params.csv"
df = CSV.read(PARAM_FILE,DataFrame)
VAH_LIST = unique!(df.cell)

dt = Dates.now()
mydt = Dates.format(dt, "yyyy-mm-dd HH:MM:SS")

report_name = "reports/summaryreport.jl"

io = open(report_name,"w")

println(io,"#' # CellFit Summary Report")
println(io,"#' #### Generated by Alec Bills at $mydt")
println(io,"#+ echo=false")
println(io,"using Plots,DataFrames,CSV")
println(io,"df = CSV.read(\"../data/params.csv\",DataFrame)")
println(io,"nothing")

for vah in VAH_LIST
    println(io,"#' #### VAH: $vah")
    println(io,"#+ echo=false")
    println(io,"ndf = filter(row->row.cell==$(vah),df)")
    println(io,"sort!(ndf,\"cycle\")")
    println(io,"nothing")
    for type in names(df)
        println(io,"#' #### VAH: $vah, PARAMETER: $type")
    println(io,"#+ echo=false")
    println(io,"plot(ndf.cycle,ndf.$type,xlabel=\"cycle\",ylabel=\"$type\",legend=false)")
    end
end

close(io)

mkdir("reports/figs")

weave("/Users/alecbills/ResearchProjects/CellFitElectrolyte/reports/summaryreport.jl"; doctype = "md2html",fig_path="figs")

rm("reports/figs",recursive=true)


